# use http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: java

jdk:
  - openjdk8

# cache local Maven repo: http://docs.travis-ci.com/user/caching/
cache:
   directories:
     - '$HOME/.m2/repository'

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  - unzip -q apache-maven-3.2.5-bin.zip
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -q apache-maven-3.5.0-bin.zip

env:
  matrix:
    - MAVEN=$PWD/apache-maven-3.2.5
    - MAVEN=$PWD/apache-maven-3.5.0

install: /bin/true
script:
  - echo $JAVA_HOME
  - export M2_HOME=$MAVEN
  - export PATH=$M2_HOME/bin:$PATH
  - mvn --version
  - mvn clean install

after_success: bash <(curl -s https://codecov.io/bash)
